<?php
/** @var \Voronin\HeightAttribute\Block\Template $block */
/** @var $viewModelHeightAttribute \Voronin\HeightAttribute\ViewModel\HeightAttribute */
$heightAttr = $block->getHeightattribute();
?>
<?php
if (($heightAttr->getProductAttributeValue() != 0) && ($heightAttr->getYesNoValue() == 'Yes')) {
    ?>
    <p>
        <strong><?= $block->escapeHtmlAttr($heightAttr->getProductAttributeLabel()); ?> : </strong>
        <?= $block->escapeHtmlAttr($heightAttr->getProductAttributeValue()); ?>
    </p>
    <?php
}
?>
