<?php
/** @var \Voronin\Cars\Block\Template $block */
/** @var $viewModelCars \Voronin\Cars\ViewModel\Cars */
$viewModelCars = $block->getViewModelCars();
$cars = $viewModelCars->getAllCars();
?>

<?php
if (count($cars) > 0): ?>

<table border="1">
    <tr>
        <th><?= __("ID") ?></th>
        <th><?= __("Model") ?></th>
        <th><?= __("Manufacturer") ?></th>
        <th><?= __("Description") ?></th>
        <th><?= __("Release Year") ?></th>
        <th><?= __("Created At") ?></th>
        <th><?= __("Updated At") ?></th>
        <th><?= __("Link to edit") ?></th>
        <th><?= __("Link to delete") ?></th>
    </tr>
    <?php foreach ($cars as $car): ?>
        <tr>
            <td><?= $block->escapeHtml($car->getId()) ?></td>
            <td><?= $block->escapeHtml($car->getCarModel()) ?></td>
            <td><?= $block->escapeHtml($car->getCarManufacturer()) ?></td>
            <td><?= $block->escapeHtml($car->getCarDescription()) ?></td>
            <td><?= $block->escapeHtml($car->getCarReleaseYear()) ?></td>
            <td><?= $block->escapeHtml($car->getCarCreatedAt()) ?></td>
            <td><?= $block->escapeHtml($car->getCarUpdatedAt()) ?></td>
            <td><a href="<?= $block->escapeUrl($block->getUrl('cars/edit/index/id/', ['id' => $car->getId()])) ?>" class="btn_a action primary" style="color: #B2D0F7"><?= __("Edit") ?></a></td>
            <td><a href="<?= $block->escapeUrl($block->getUrl('cars/delete/index/id/', ['id' => $car->getId()])) ?>" class="btn_a action primary" style="color: black"><?= __("Delete") ?></a></td>
        </tr>
    <?php endforeach; ?>
</table>
    <?php else :?>
    <h1><?= __("There is no car to display.") ?></h1>
<?php endif;?>
    <hr />
<a href="<?= $block->escapeHtml($block->getUrl('cars/add')) ?>" class="btn_a action primary"><?= __("Add car")?></a>
