<?php
/** @var \Voronin\Cars\Block\Template $block */
/** @var $viewModelCars \Voronin\Cars\ViewModel\Cars */
$viewModelCars = $block->getViewModelCars();
$cars = $viewModelCars->getAllCars();
?>

<?php
if (count($cars) > 0): ?>

<table border="1">
    <tr align="center">
        <th><?= $block->escapehtml(__("ID")) ?></th>
        <th><?= $block->escapehtml(__("Model")) ?></th>
        <th><?= $block->escapehtml(__("Manufacturer")) ?></th>
        <th><?= $block->escapehtml(__("Description")) ?></th>
        <th><?= $block->escapehtml(__("Release Year")) ?></th>
        <th><?= $block->escapehtml(__("Created At")) ?></th>
        <th><?= $block->escapehtml(__("Updated At")) ?></th>
        <th><?= $block->escapehtml(__("Link to edit")) ?></th>
        <th><?= $block->escapehtml(__("Link to delete")) ?></th>
    </tr>
    <?php foreach ($cars as $car): ?>
        <tr>
            <td align="center"><?= $block->escapeHtml($car->getId()) ?></td>
            <td align="center"><?= $block->escapeHtml($car->getCarModel()) ?></td>
            <td align="center"><?= $block->escapeHtml($car->getCarManufacturer()) ?></td>
            <td align="center"><?= $block->escapeHtml($car->getCarDescription()) ?></td>
            <td align="center"><?= $block->escapeHtml($car->getCarReleaseYear()) ?></td>
            <td align="center"><?= $block->escapeHtml($car->getCarCreatedAt()) ?></td>
            <td align="center"><?= $block->escapeHtml($car->getCarUpdatedAt()) ?></td>
            <td align="center">
                <a href="<?= $block->escapeUrl($block->getUrl('cars/edit/index/id/', ['id' => $car->getId()])) ?>"
                   class="btn_a action primary" style="color: #B2D0F7"><?= $block->escapehtml(__("Edit")) ?>
                </a>
            </td>
            <td align="center">
                <a href="<?= $block->escapeUrl($block->getUrl('cars/delete/index/id/', ['id' => $car->getId()])) ?>"
                   class="btn_a action primary" style="color: black"><?= $block->escapehtml(__("Delete")) ?>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
    <?php else:?>
    <h1><?= $block->escapehtml(__("There is no car to display.")) ?></h1>
<?php endif;?>
    <hr />
<a href="<?= $block->escapeHtml($block->getUrl('cars/add')) ?>" class="btn_a action primary">
    <?= $block->escapehtml(__("Add car")) ?>
</a>
